### PR TITLE
Integrate cute_sound.h

### PR DESCRIPTION
**Pull request by RandyGaul**
Hey Noel, this is totally just for fun. From watching your streams it looks like you mostly enjoy learning about new things and probably want to implement your own audio thing, or maybe integrate e.g. SoLoud, who knows. But, out of curiosity I wanted to see how quickly I could integrate cute_sound.h into your framework.

You have a very well written framework Noel! It was super easy to get it going. I haven't tested it hardly at all yet, but maybe next weekend I can hook up some audio to TinyLink or something and see how that goes.

If you had any thoughts about the audio API I designed here let me know! Super curious what you might think about it, or how it might compare to your audio setup via FMOD in your weekend project.

Things cute_sound.h does that might be kinda cool:

* Natively runs on Apple/Windows machines
* SDL2 support for everywhere else (though there's a define `CUTE_SOUND_FORCE_SDL` I turned on for blah)
* Sound vs music abstraction
* Wav + OGG loading from disk or memory
* Global controls for volume, panning, etc.
* Refcounted audio sources. I personally don't enjoy refcounted pointers, but I mimic'd how you setup your Font API for consistency
* Music fade in/out + crossfade

### CODE REVIEW

**Comment by NoelFB** [comment]
This looks really cool, Randy! Thanks for exploring this. I think I'll likely merge this in - just want to read it over and haven't had a chance to yet.

And yeah, I opted to do refcounted resources for simplicity, but I agree it may not be super ideal... I'm not sure if I'll refactor that long-term but I think keeping them the same across resources is good for now.

**Comment by RandyGaul** [comment]
Wow cool! Okay, in that case let me do some testing. I'll post back when I can confirm it's actually working properly.

Refcounting is going to behave a lot like C# so I can see why you chose this style. It can also be quite simple from a user perspective, especially for a new set of eyes.

**Comment by NoelFB** [comment]
Cool :) yeah when I get a chance I'll also mess around with it a bit. I like the layout of it though!

**Comment by RandyGaul** [comment]
I needed to push a modification to cute_sound.h to support destroying audio sources after calling `cs_shutdown` to support refcounting properly. Also had to do some other little tweaks here and there. Got some audio working for tinylink. I'll post PR here shortly.

Do you want a PR for tinylink as well?

**Comment by NoelFB** [comment]
Oh sure! that sounds cool. I think tinylink is probably outdated as I haven't updated it in a while, but if it wasn't too bad that sounds great!

**Comment by RandyGaul** [comment]
Okay looks mostly good to try out now https://github.com/NoelFB/tiny_link/pull/7

**Comment by NoelFB** [comment]
Awesome, this works great! I'm inclined to merge it in if you're cool with it!

**Comment by NoelFB** [comment]
Actually, there's one thing I want to consider before merging this in... if for some reason the platform isn't SDL2, I may want to account for that. Just messing around with that a bit.

**Comment by RandyGaul** [comment]
Yeah if you find that CUTE_SOUND_FORCE_SDL macro you can control if it uses SDL or run natively on apple machine + windows. If you delete this before including cute_sound.h it will detect difectsound for windows or coreaudio for apple devices. For Linux/Android I’d say SDL is the way to go.

I wasn’t sure how you want to set it up. Maybe you wanna merge and then make some edits yourself?

**Comment by NoelFB** [comment]
Yeah! I think I might merge and then tweak it a bit. This is extremely solid though, I like how it works :) Thanks for spending time iterating on this!

(I'm basically trying to decide if I abstract it further into like, `blah_audio_sdl2` like I do with platforms & renderers... seems kind of overkill though. We'll see!)

**Comment by NoelFB** [comment]
(Another thing I'm considering long-term is to just remove almost all platform-layer abstractions and just use SDL2 since it hits like every target anyway, especially once SDL-GPU comes into play haha)

**Comment by RandyGaul** [comment]
Yeah I am really leaning that way too. SDL is just really good for platform abstractions. I also spent time learning to make my own platform layers just like you did then ended up using SDL since it’s code quality is just so high.

If you wanted to abstract audio backends I like how soloud does it. The low level native audio APIs all expose some kind of ring buffer for filling samples. Most of them have a callback API where it requests you to memcpy samples into a buffer (SDL, ALSA, CoreAudio all do this). Then you can do your own mixing in portable C (this is what cute_sound.h does). The platform audio layer becomes very tiny for this design.

Just my 2 cents for discussion 😊

**Comment by NoelFB** [comment]
Yeah I'm leaning that direction re: SDL2
Merging this in! I might end up just dropping platform abstractions soon ....

**Pull request merged**
