### PR TITLE
SDL2 downloaded from the web

### PR DESCRIPTION
**Pull request by svercl**
This change makes it so that SDL2 is downloaded from the internet and is built locally.

Also included a little modification for Emscripten, you can keep as is or revert it. I also tested this with Emscripten and it works fine. 

Let me know if there's anything missing from this PR.

### CODE REVIEW

**Review by vtfg — APPROVED** [review]
It works! Thank's man, I was having a problem on including SDL2 and now it's solved.

**Comment by NoelFB** [comment]
This looks cool! I'm hesitant to make the default be compiling SDL2, but maybe it could be an option? I'll give this a shot in a little while.

**Comment by svercl** [comment]
Yeah, the plan was to default to using system SDL2, but fallback to compiling from source if it's not available. I haven't had much time to work on that quite yet, but it should be doable by checking for ${sdl2_FOUND} or similar.

**Comment by NoelFB** [comment]
Sorry I haven't merged this in yet, I've been doing various refactors but I think I'd like to!
I think it makes sense for it to attempt to find the SDL package first, and if that fails, then download it ... I can try merging yours in later and doing that.

**Comment by svercl** [comment]
I'm not great at CMake, but I did add checking for SDL2 locally first, and then downloading it. Feel free to clean it up! :)

**Comment by NoelFB** [comment]
Ah you're right! I tweaked it a bit to keep some values I wanted and merged it! :)

**Pull request merged**
