### PR TITLE
Simple github release workflow for CI

### PR DESCRIPTION
**Pull request by benjitrosch**
Saw that #31 was removed so thought I would offer up my own take on the PR.

I've kept the build process as simple as possible, and left some comments so you can know what each step does. I'm creating a separate job for each platform (windows, mac, linux, you can add more e.g. different windows versions or linux distros) and verifying that the CMake build step completes without errors.

Let me know if you have any questions, and happy to make any changes!

image

### CODE REVIEW

**Comment by NoelFB** [comment]
Thanks! I'll merge this in and try it out, it looks good!

**Comment by NoelFB** [comment]
It seems like the initial action failed, with this error:

```
actions/checkout@master is not allowed to be used in NoelFB/blah. Actions in this workflow must be: within a repository owned by NoelFB.
```

I'm not sure if this is something that will just work now that it's merged in. I don't totally understand the action system so need to spend some time reading up on it.

**Comment by benjitrosch** [comment]
@NoelFB weird, works on my [forked branch](https://github.com/benjitrosch/blah/actions). Based on the error message, it's likely related to Action's permissions for this repo specifically?

Here's how it looks on my fork:

image

**Comment by benjitrosch** [comment]
@NoelFB Managed to reproduce the error you've having by messing with my Actions permissions.  I changed to this setting:

Screen Shot 2023-03-04 at 5 41 29 PM

And sure enough, got the same error...

Screen Shot 2023-03-04 at 5 41 42 PM

You might want to try the last option, which allows you to choose `Allow actions created by GitHub` which will make this work.

**Comment by NoelFB** [comment]
Ah awesome, thanks! Should be working now, I wasn't aware of the action permissions!

**Comment by RandyGaul** [comment]
Trying to learn how to use workflow stuff myself. How does this work on Linux? I'm trying with some of my own code, and it's failing on Ubuntu since OpenGL wasn't installed. Doesn't Blah also link against SDL2/OpenGL on Linux?

**Comment by RandyGaul** [comment]
I ended having to add a few lines to the workflow file for Linux https://github.com/RandyGaul/cute_framework/actions/runs/4350093933/workflow

```yaml

      - name: Install OpenGL
        run: |
          sudo apt-get update -qq
          sudo apt-get install gcc-multilib
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
        if: matrix.platform.name == 'Linux'
```

**Comment by benjitrosch** [comment]
@RandyGaul glad to see you got it working for cute framework!

**Comment by RandyGaul** [comment]
@benjitrosch Any insight on how it's working here without installing OpenGL?

**Comment by benjitrosch** [comment]
@RandyGaul Took a look, and seems the [line](https://github.com/RandyGaul/cute_framework/blob/0b8720ebd78c24b43cbbf350a800cc836217f4a5/CMakeLists.txt#L275) responsible for that in your CMakeLists.txt is:
```cmake
find_package(OpenGL REQUIRED)
```
Removing this would allow that step to succeed, but it would then fail on the next step because `sokol_gfx.h` includes it:
```cpp
#include <GL/gl.h>
```
from this line which applies to linux: https://github.com/floooh/sokol/blob/956a0d8c996a611979a706a233a0c38e1ea9ae92/sokol_gfx.h#L3323

You could get around this if you define [SOKOL_EXTERNAL_GL_LOADER](https://github.com/floooh/sokol/blob/956a0d8c996a611979a706a233a0c38e1ea9ae92/sokol_gfx.h#L48) but then you have to go through the trouble of writing all the OpenGL bindings [like blah does](https://github.com/NoelFB/blah/blob/45a5e8839f96d322b25069d594c908a3452e6605/src/internal/blah_platform_sdl2.cpp#L582) using SDL2's `SDL_GL_GetProcAddress()`.

**Comment by RandyGaul** [comment]
@benjitrosch Gotchaaa, that's super helpful! Thanks so much for helping out. CMake related things are pretty difficult for me to learn, so this is super appreciated!

**Comment by benjitrosch** [comment]
@RandyGaul happy to help! It confuses me too most of the time 😄

**Comment by NoelFB** [comment]
Yeah I opted to go the route of using `SDL_GL_GetProcAddress`.... bit more setup code but then it makes portability a bit easier because it doesn't rely on external libraries...

**Pull request merged**
