### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by SushilRagoonath**
Fixed win32 compile error.
Also basic CI to check whether latest code compiling. Its cool if you don't want it I'll keep it on mine

### CODE REVIEW

**Comment by NoelFB** [comment]
Oh cool! I like that idea, I've wanted to set up actions but never really learned how to. I'll merge this.

**Comment by RandyGaul** [comment]
What is `lukka/get-cmake@latest` ?

**Comment by NoelFB** [comment]
ah yeah, gonna remove for the moment, will revisit later. I like the idea to add some simple building actions in the future though.

**Comment by RandyGaul** [comment]
It was some kind of build action? I'm new to this thing so don't really know what's going on

**Comment by SushilRagoonath** [comment]
It is a third-party build action that installs cmake.
I wasn't sure if the default build environment comes with cmake or not. I'll test now if its really necessary.

Edit: tested is and cmake is there, so the extra action is not required.

**Pull request merged**
