### PR TITLE
fix: stackvector expand

### PR DESCRIPTION
**Pull request by bitwitch**
I found your game framework/engine/thing and checked out a couple of your archived streams. I am using it as a learning resource for my own game project. I tried to build the library and hit the following error:

stackvector.h:132:32: error: use of undeclared identifier 'item'
                                new (data() + count + i) T(item);

It appears that the StackVector::expand function has a little copy paste error on line 132. When expanding a vector, empty type T's should be added to the vector instead of trying to copy the non-existent T, 'item'.

Thanks for making this available for all of us out here.

### CODE REVIEW

**Comment by RandyGaul** [comment]
Just curious, did you try building with something other than visual studio?

**Comment by bitwitch** [comment]
@RandyGaul Yeah, I am on a mac so I just built using cmake.

**Comment by RandyGaul** [comment]
Ah, yes on visual studio it doesn’t compile unused templated member functions, so it’s easy to miss little things like this :)

**Comment by bitwitch** [comment]
Oh interesting. Also interesting that just a couple days ago I was reading an article you wrote: [Spaces: Useful Game Object Containers](https://gamedevelopment.tutsplus.com/tutorials/spaces-useful-game-object-containers--gamedev-14091).

**Comment by NoelFB** [comment]
Ah yeah, that's my bad! I hadn't tested outside visual studio in a while so missed this. Thanks!

**Pull request merged**
